### ISSUE TITLE
TODO by nQuisition#1284

### ISSUE THREAD

**Issue by nQuisition** [nQuisition/HooksTest#6]
**Submitted by**
nQuisition#1284

**Content**
- [x] Write code 
- [x] Get a nice hat 
- [ ] Make dinner
- [ ] Do something fun!
- [ ] Get more food! 
- [ ] Get more drinks!! 
- [ ] Go to sleep
